type Pokemon {
  id: ID!
  name: String!
  image_url: String!
  info: PokemonInfo
}

enum PokemonType {
  electric
  water
  fire
}

type PokemonInfo {
  id: ID!
  type: PokemonType!
  pokemonId: ID!
  evolutions: [PokemonEvolution]
}

type PokemonEvolution {
  id: ID!
  name: String!
  pokemonInfoId: ID!
}

input FindPokemonWhereInput {
  id: ID
  name: String
}

type Query {
  pokemons: [Pokemon!]!
  pokemon(where: FindPokemonWhereInput!): Pokemon
}

input UpdatePokemonInput {
  name: String
  type: PokemonType
}

type Mutation {
  updatePokemon(id: ID!, data: UpdatePokemonInput!): Pokemon
}